# global:

redis_host: my-localhost

postgres:
  adminUser: postgres
  adminPassword: postgres
  db_host: my-localhost
  db_port: '5432'
  superset:
    db_name: superset
    db_username: superset
    db_password: superset123

image:
  repository: sanketikahub/superset
  tag: 3.0.2
  pullPolicy: IfNotPresent

redis_url: 'redis://my-localhost:6379/3'

web_console_base_url: 'my-localhost:3000/console'
superset_base_url: 'my-localhost:8088'

extraSecrets: {}
extraConfigs: {}

configOverrides:
  enable_feature_flags: |
    FEATURE_FLAGS = {
      "DASHBOARD_NATIVE_FILTERS": True,
      "DASHBOARD_CROSS_FILTERS": True,
      "DASHBOARD_NATIVE_FILTERS_SET": True,
      "ENABLE_TEMPLATE_PROCESSING": True,
    }

  data_cache_config: |
    DATA_CACHE_CONFIG = {
      'CACHE_TYPE': 'redis',
      'CACHE_DEFAULT_TIMEOUT': 600,
      'CACHE_KEY_PREFIX': 'superset_',
      'CACHE_REDIS_URL': '{{ tpl .Values.redis_url . }}'
    }

  sql_alchemy_config: |
    SQLALCHEMY_DATABASE_URI = 'postgresql://{{ tpl .Values.postgres.superset.db_username . }}:{{ tpl .Values.postgres.superset.db_password . }}@{{ tpl .Values.postgres.db_host . }}/{{ tpl .Values.postgres.superset.db_name . }}'
    SQLALCHEMY_TRACK_MODIFICATIONS = True
    SECRET_KEY = '4/SLqE9vfrZsrF4YTVFVfmZDiW4Q0DKh0dHBoqHWC3Lhpgktph/jfkUI'

service:
  type: LoadBalancer
